### ISSUE TITLE
Android.Content.Res.Resources NotFoundException in Kitkat android device while using Artina Button.

### ISSUE THREAD

**Issue by tellamon** [UXDivers/Grial-UI-Kit-Support#128]
I'm using Artina button as below in my code

`var butRegister = new UXDivers.Artina.Shared.Button();`

That work in a Lollipop device but crash in a Kitkat device with following exception.

```
12-20 14:27:18.370: E/AndroidRuntime(17858): FATAL EXCEPTION: main
12-20 14:27:18.370: E/AndroidRuntime(17858): Process: com.bunticket.droid, PID: 17858
12-20 14:27:18.370: E/AndroidRuntime(17858): android.content.res.Resources$NotFoundException: File res/layout/preference_header_item.xml from color state list resource ID #0x1090099
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.content.res.Resources.loadColorStateList(Resources.java:3623)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.content.res.TypedArray.getColor(TypedArray.java:320)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onCreateView(Native Method)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onCreateView(FragmentContainer.java:51)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.os.Handler.handleCallback(Handler.java:733)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.os.Looper.loop(Looper.java:146)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.app.ActivityThread.main(ActivityThread.java:5635)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at java.lang.reflect.Method.invoke(Method.java:515)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at dalvik.system.NativeStart.main(Native Method)
12-20 14:27:18.370: E/AndroidRuntime(17858): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: invalid drawable tag LinearLayout
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:146)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.content.res.ColorStateList.createFromXml(ColorStateList.java:129)
12-20 14:27:18.370: E/AndroidRuntime(17858): 	at android.content.res.Resources.loadColorStateList(Resources.java:3619)
```

I had some problem using artina button before but solved with [imports](https://github.com/UXDivers/Grial-UI-Kit-Support/issues/82#issuecomment-257888038)

**Comment by jpbrocca** [comment]
Hi @tellamon, 
can you send an email to:
hello@uxdivers.com

with your purchase details (order number, complete name, email) so we can send you the fix?

Best regards,
JP

**Comment by tellamon** [comment]
@jpbrocca, Thanks

grial-uikit-1.5.2 fixed this issue.

**Comment by jpbrocca** [comment]
Hi @tellamon,

Great. Please remember to close issues after resolución ;).

Thanks,
JP

**Comment by tellamon** [comment]
@jpbrocca , I tried but it looks like I don't have such permission. Do I?

**Comment by jpbrocca** [comment]
@tellamon yes, you should be able to close issues.
