### ISSUE TITLE
Android exception

### ISSUE THREAD

**Issue by philggg** [UXDivers/Grial-UI-Kit-Support#142]
I am trying to run the latest sample project. (v1.5)
I ran it initially with  Xamarin Forms (V 2.2.031)
It build OKs on both Visual Studio and Xamerin Studio (Mac).
IOS version works fine.  But Android version (running on a Samsung SM-T310 Android 3.1) ) fails.
(both with Visual Studio (PC) and Xamarin Studio (Mac)
It deploys to the device, brings up the splash screen then fails.

Then I updated Xamarin Forms to version 2.3.3.193)  Same error.

(The Grial sample that is available from the Google Play store works OK on the device)

Here is a snapshot of the log file.
02-26 17:10:13.465 D/Mono    ( 6601): [0x7f2b3aa8] hill climbing, change max number of threads 3
02-26 17:10:13.495 D/Mono    ( 6601): [0x7f1604a0] hill climbing, change max number of threads 9
02-26 17:10:13.505 D/OpenGLRenderer( 6601): Enabling debug mode 0
02-26 17:10:13.590 D/Mono    ( 6601): [0x7f2b3aa8] hill climbing, change max number of threads 3
02-26 17:10:13.740 I/dalvikvm( 6601): Could not find method android.widget.ImageView.<init>, referenced from method md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsImageView.<init>
02-26 17:10:13.740 W/dalvikvm( 6601): VFY: unable to resolve direct method 21288: Landroid/widget/ImageView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
02-26 17:10:13.740 D/dalvikvm( 6601): VFY: replacing opcode 0x70 at 0x0000
02-26 17:10:13.750 D/Mono    ( 6601): [0x7f94d120] hill climbing, change max number of threads 2
02-26 17:10:13.825 D/Mono    ( 6601): DllImport searching in: '__Internal' ('(null)').
02-26 17:10:13.825 D/Mono    ( 6601): Searching for 'java_interop_jnienv_get_static_object_field'.
02-26 17:10:13.825 D/Mono    ( 6601): Probing 'java_interop_jnienv_get_static_object_field'.
02-26 17:10:13.825 D/Mono    ( 6601): Found as 'java_interop_jnienv_get_static_object_field'.
02-26 17:10:13.850 D/Mono    ( 6601): Assembly Ref addref UXDivers.Artina.Shared.Droid[0x72e33770] -> Xamarin.Forms.Core[0x74a09500]: 8
02-26 17:10:13.935 I/dalvikvm( 6601): Could not find method android.widget.TextView.<init>, referenced from method md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsTextView.<init>
02-26 17:10:13.935 W/dalvikvm( 6601): VFY: unable to resolve direct method 21599: Landroid/widget/TextView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
02-26 17:10:13.935 D/dalvikvm( 6601): VFY: replacing opcode 0x70 at 0x0000
02-26 17:10:14.060 D/Mono    ( 6601): Assembly Ref addref UXDivers.Artina.Shared.Droid[0x72e33770] -> System[0x7e2aa298]: 9
02-26 17:10:14.080 D/Mono    ( 6601): Assembly Ref addref UXDivers.Artina.Shared.Droid[0x72e33770] -> Xamarin.Android.Support.v7.AppCompat[0x7488c008]: 3
02-26 17:10:14.140 D/Mono    ( 6601): DllImport searching in: '__Internal' ('(null)').
02-26 17:10:14.140 D/Mono    ( 6601): Searching for 'java_interop_jnienv_call_float_method_a'.
02-26 17:10:14.140 D/Mono    ( 6601): Probing 'java_interop_jnienv_call_float_method_a'.
02-26 17:10:14.140 D/Mono    ( 6601): Found as 'java_interop_jnienv_call_float_method_a'.
02-26 17:10:14.175 D/Mono    ( 6601): DllImport searching in: '__Internal' ('(null)').
02-26 17:10:14.175 D/Mono    ( 6601): Searching for 'java_interop_jnienv_new_object_array'.
02-26 17:10:14.175 D/Mono    ( 6601): Probing 'java_interop_jnienv_new_object_array'.
02-26 17:10:14.175 D/Mono    ( 6601): Found as 'java_interop_jnienv_new_object_array'.
02-26 17:10:14.185 D/Mono    ( 6601): DllImport searching in: '__Internal' ('(null)').
02-26 17:10:14.185 D/Mono    ( 6601): Searching for 'java_interop_jnienv_set_object_array_element'.
02-26 17:10:14.185 D/Mono    ( 6601): Probing 'java_interop_jnienv_set_object_array_element'.
02-26 17:10:14.185 D/Mono    ( 6601): Found as 'java_interop_jnienv_set_object_array_element'.
02-26 17:10:14.195 D/Mono    ( 6601): DllImport searching in: '__Internal' ('(null)').
02-26 17:10:14.195 D/Mono    ( 6601): Searching for 'java_interop_jnienv_get_object_array_element'.
02-26 17:10:14.195 D/Mono    ( 6601): Probing 'java_interop_jnienv_get_object_array_element'.
02-26 17:10:14.195 D/Mono    ( 6601): Found as 'java_interop_jnienv_get_object_array_element'.
02-26 17:10:14.205 D/Mono    ( 6601): DllImport searching in: '__Internal' ('(null)').
02-26 17:10:14.205 D/Mono    ( 6601): Searching for 'java_interop_jnienv_is_assignable_from'.
02-26 17:10:14.205 D/Mono    ( 6601): Probing 'java_interop_jnienv_is_assignable_from'.
02-26 17:10:14.205 D/Mono    ( 6601): Found as 'java_interop_jnienv_is_assignable_from'.
02-26 17:10:14.220 D/Mono    ( 6601): Assembly Ref addref UXDivers.Artina.Shared.Droid[0x72e33770] -> UXDivers.Artina.Shared[0x72d378c8]: 3
An unhandled exception occured.

Any help would be appreciated.
Phil

**Comment by jpbrocca** [comment]
Hi @philggg,
That is weird, especially if it the Google Play app runs on same device.

Are you only trying on Samsung SM-T310?
What happens if you try on any other android device?

Best,
JP

**Comment by philggg** [comment]
I tried it with a newer Android device (Nougat 6.0.1) and it worked.  I reran it on the Samsung 4.4.2 device and it still failed.)   

Since I can proceed for now I will mark it as closed but I am sure others will have this problem.
thanks
Phil

The error (from Xamarin Studio on Mac ) on the 4.4.2 device is
Java.Lang.UnsupportedOperationException: Can't convert to color: type=0x5
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
  at Java.Interop.JniEnvironment+InstanceMethods.CallIntMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00085] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11484
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00031] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:206
  at Android.Content.Res.TypedArray.GetColor (System.Int32 index, System.Int32 defValue) [0x0002a] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Content.Res.TypedArray.cs:205
  at UXDivers.Artina.Shared.ArtinaButtonRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x0014b] in <105d0c26fe664c40aab4b456890f6304>:0
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000f4] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:193
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:129
  at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x0001f] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289
  at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00023] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:74
  at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00104] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:207
  at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:58
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:337
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x00111] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:196
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:129
  at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x0001f] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289
  at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00023] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:74
  at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00104] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:207
  at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:58
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:337
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x00111] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:196
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:129
  at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x0001f] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289
  at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00023] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:74
  at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00104] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:207
  at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:58
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:337
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x00111] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:196
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:129
  at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager) [0x00031] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:325
  at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState) [0x00008] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:66
  at Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) [0x00022] in <27c17fe440cf491ba8255bcefade6e02>:0
  at at (wrapper dynamic-method) System.Object:aaaebe11-720b-4fbf-ac54-9c35bedf2190 (intptr,intptr,intptr,intptr,intptr)
  at java.lang.UnsupportedOperationException: Can't convert to color: type=0x5
  at at android.content.res.TypedArray.getColor(TypedArray.java:327)
  at at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onCreateView(Native Method)
  at at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onCreateView(FragmentContainer.java:51)
  at at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
  at at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
  at at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
  at at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
  at at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
  at at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
  at at android.os.Handler.handleCallback(Handler.java:733)
  at at android.os.Handler.dispatchMessage(Handler.java:95)
  at at android.os.Looper.loop(Looper.java:146)
  at at android.app.ActivityThread.main(ActivityThread.java:5593)
  at at java.lang.reflect.Method.invokeNative(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:515)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
  at at dalvik.system.NativeStart.main(Native Method)

**Comment by jpbrocca** [comment]
Hi @philggg, thanks for the details.
Can you send an email to:

hello@uxdivers.com

...with your order number, name and purchase date so I can send you an update?
I am not sure but I think that maybe you don't have the latest version.

Best regards and thanks,
JP

**Comment by softsan** [comment]
We encounter with the below issue on android 4.4 

Java.Interop.JniEnvironmentFile res/layout/preference_list_content.xml from color state list resource ID #0x10900a0
Raw
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<9041c67d85b04791a03581ef7352975d>:0
Java.Interop.JniEnvironment.InstanceMethods.CallIntMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args)<8e5f7a1f53ef4978aae1abfbd57b0680>:0
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualInt32Method(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<8e5f7a1f53ef4978aae1abfbd57b0680>:0
Android.Content.Res.TypedArray.GetColor(int index, int defValue)<fea80d5cbdd3463abd216ff1c7f3ea8c>:0
UXDivers.Artina.Shared.ArtinaButtonRenderer.OnElementChanged(ElementChangedEventArgs<TElement> e)<105d0c26fe664c40aab4b456890f6304>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(TElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(VisualElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild(VisualElement view, IVisualElementRenderer oldRenderer, RendererPool pool, bool sameChildren)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement(VisualElement oldElement, VisualElement newElement)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.Load()<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetPackager(VisualElementPackager packager)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(TElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(VisualElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild(VisualElement view, IVisualElementRenderer oldRenderer, RendererPool pool, bool sameChildren)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement(VisualElement oldElement, VisualElement newElement)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.Load()<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetPackager(VisualElementPackager packager)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(TElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(VisualElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild(VisualElement view, IVisualElementRenderer oldRenderer, RendererPool pool, bool sameChildren)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement(VisualElement oldElement, VisualElement newElement)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.Load()<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetPackager(VisualElementPackager packager)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(TElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(VisualElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild(VisualElement view, IVisualElementRenderer oldRenderer, RendererPool pool, bool sameChildren)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement(VisualElement oldElement, VisualElement newElement)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.Load()<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetPackager(VisualElementPackager packager)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(TElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(VisualElement element)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element, FragmentManager fragmentManager)<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)<1481f85a917c4f2b882ea161e9bc082f>:0
Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState)<27c17fe440cf491ba8255bcefade6e02>:0
at (wrapper dynamic-method) System.Object:bdae7774-8b07-4877-9e58-a7d807b52a0a (intptr,intptr,intptr,intptr,intptr)
--- End of managed Java.Lang.RuntimeException stack trace ---
android.content.res.Resources$NotFoundException: File res/layout/preference_list_content.xml from color state list resource ID #0x10900a0
at android.content.res.Resources.loadColorStateList(Resources.java:3169)
at android.content.res.TypedArray.getColor(TypedArray.java:320)
md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onCreateView(Native Method)
at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onCreateView(FragmentContainer.java:51)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5377)
java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
dalvik.system.NativeStart.main(Native Method)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #21: invalid drawable tag LinearLayout
at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:146)
at android.content.res.ColorStateList.createFromXml(ColorStateList.java:129)
at android.content.res.Resources.loadColorStateList(Resources.java:3165)
... 18 more
java.lang.reflectBinary XML file line #21: invalid drawable tag LinearLayout
--- End of managed Org.XmlPull.V1.XmlPullParserException stack trace ---
org.xmlpull.v1.XmlPullParserException: Binary XML file line #21: invalid drawable tag LinearLayout
at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:146)
at android.content.res.ColorStateList.createFromXml(ColorStateList.java:129)
at android.content.res.Resources.loadColorStateList(Resources.java:3165)
at android.content.res.TypedArray.getColor(TypedArray.java:320)
md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onCreateView(Native Method)
at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onCreateView(FragmentContainer.java:51)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5377)
java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
dalvik.system.NativeStart.main(Native Method)
