### ISSUE TITLE
Unable to change accent color in Android - Java Exception: A TaskDescription's primary color should be opaque

### ISSUE THREAD

**Issue by ahmedkhan25** [UXDivers/Grial-UI-Kit-Support#17]
I'm trying to change the app's Accent color in Android:
1.  I changed the Accent Color property in App.xaml to #169CEE
2. I processed the Colors.tt file located in PCL project and rebuilt
3. In the Droid Project I processed the Colors.tt file and rebuild

the Colors.xml filein droid is now:

```
<!-- Artina Exported Colors -->
<color name="AccentColor">#00169CEE</color>
<color name="InverseTextColor">#FFFFFFFF</color>
```

but when I try to run in the debugger I'm getting the following runtime exception:

perhaps related to this SO post?
http://stackoverflow.com/questions/29166809/5-1-crash-a-taskdescriptions-primary-color-should-be-opaque

Java.Lang.RuntimeException: Unable to start activity ComponentInfo{com.IncidentZero/md59272df42807eab04ee47c628316928bc.MainActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque ---> Java.Lang.RuntimeException: A TaskDescription's primary color should be opaque
  at --- End of managed exception stack trace ---
  at java.lang.RuntimeException: A TaskDescription's primary color should be opaque
  at at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:543)
  at at android.app.Activity.onApplyThemeResource(Activity.java:3686)
  at at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
  at at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2271)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
  at at android.app.ActivityThread.access$800(ActivityThread.java:151)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:135)
  at at android.app.ActivityThread.main(ActivityThread.java:5254)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:372)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
  --- End of inner exception stack trace ---
  at --- End of managed exception stack trace ---
  at java.lang.RuntimeException: Unable to start activity ComponentInfo{com.IncidentZero/md59272df42807eab04ee47c628316928bc.MainActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
  at at android.app.ActivityThread.access$800(ActivityThread.java:151)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:135)
  at at android.app.ActivityThread.main(ActivityThread.java:5254)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:372)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
  at Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
  at at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:543)
  at at android.app.Activity.onApplyThemeResource(Activity.java:3686)
  at at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
  at at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2271)
  at ... 10 more

**Comment by jpbrocca** [comment]
Hi @ahmedkhan25.

In order to make the compilation without failing please add the "FF" to your color.
So instead of using:

`#169CEE`

use:

`#FF169CEE`

Best,
JP

**Comment by cbartonnh** [comment]
Just looking at the Accent Color, wouldn’t 00 for the color’s alpha be completely invisible? That is why it is complaining. Maybe you need to specify #FF169CEE in App.xml?

**Comment by jpbrocca** [comment]
That is right @cbartonnh...thanks for your help!

**Comment by ahmedkhan25** [comment]
In the shared App.xaml (PCL) its '#169CEE' which works fine with iOS

but  directly putting in FF  in colors.xml resolved the issue-   

thanks -but just a heads up the T4 template needs to be corrected for this droid part

**Comment by jpbrocca** [comment]
Yes @ahmedkhan25, that is a good suggestion.
Thanks for it!

**Comment by am9072** [comment]
ell..!! this is the error only because of primary color opaqueness

go to your res-->values-->color.xml
and remove two digits of primary color

watch video for more easiness.
https://youtu.be/pLO9KzxG--k
