### ISSUE TITLE
Support for effects:Effects.Outline="1"

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#242]
Hi Grial team,

I am using Grid with Effect's CornerRadius. Is there a support for Outline (Border) so that we can have a Grid with white background sit on the StackLayout which also white background.

Thanks.
Dennis

**Comment by jpbrocca** [comment]
Hi @define, how are you?

Unfortunately, there is no outline effect.
I am not sure what you want to achieve.
Can you add an image showing what this would be?

Best
JP

**Comment by denfung** [comment]
Hi JP,

Please find below for the grid outline that I tried to achieve. 

![grid outline](https://user-images.githubusercontent.com/23342040/30432681-f9b9f832-9994-11e7-9643-c5522809e835.png)

Any recommendation with Grial UI Kit?

Dennis

**Comment by jpbrocca** [comment]
Hi @denfung, how are you?

Yes, you can achieve that through a <Frame> element.
Basically, something like this:

```
<Frame 
	OutlineColor="#f1f1f1" 
	HasShadow="false" 
	Padding="10"
	CornerRadius="4">
	<Grid>
		<Grid.ColumnDefinitions>
			<ColumnDefinition Width="48" />
			<ColumnDefinition Width="*" />
			<ColumnDefinition Width="48" />
		</Grid.ColumnDefinitions>
		<Label 
			Grid.Row="0" 
			Grid.Column="0" 
			HorizontalTextAlignment="Center"
			Text="+" />
		<Label 
			Grid.Row="0" 
			Grid.Column="1"
			HorizontalTextAlignment="Center" 
			Text="1" />
		<Label 
			Grid.Row="0" 
			Grid.Column="2" 
			HorizontalTextAlignment="Center"
			Text="-" />
	</Grid>
</Frame>
```
You should see something like the following:
![image](https://user-images.githubusercontent.com/15996999/30446369-55a7625a-995f-11e7-80d4-6102a9443ded.png)

Hope that helps.
Regards,
JP

**Comment by denfung** [comment]
Hi @jpbrocca ,

Thanks for the recommendation.
It seem like the frame with outline is not working on Xamarin Android. 

Regards,
Dennis

**Comment by jpbrocca** [comment]
Hi @denfung,

OK, the alternative is you try something like the following

**Style**:

```
<Style x:Key="FakeRoundedGrid" TargetType="Frame">                
       <Setter Property="effects:Effects.CornerRadius" Value="2" />
</Style>
```
**The Grid:**

```
<Grid 
    BackgroundColor="Gray" 
    Style="{ StaticResource FakeRoundedGrid }">

    <Grid 
        Margin="1" 
        BackgroundColor="White">

        <Grid.RowDefinitions>
            <RowDefinition Height="48" />
        </Grid.RowDefinitions>
        
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="48" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="48" />
        </Grid.ColumnDefinitions>
        
        <Label 
            Grid.Row="0" 
            Grid.Column="0" 
            HorizontalTextAlignment="Center"
            VerticalOptions="Center"
            Text="+" />
        <Label 
            Grid.Row="0" 
            Grid.Column="1"
            HorizontalTextAlignment="Center" 
            VerticalOptions="Center"
            Text="1" />
        <Label 
            Grid.Row="0" 
            Grid.Column="2" 
            HorizontalTextAlignment="Center"
            VerticalOptions="Center"
            Text="-" />
    </Grid>
</Grid>
```

Even it is not perfect, it won't be that far from what you need to recreate:

![image](https://user-images.githubusercontent.com/15996999/30495921-44cc2ba8-9a24-11e7-8aa1-784d8f2e92bf.png)

**Comment by sadranyi** [comment]
Hi we have been having these error when trying to publish a release version of our app. find below the log


FATAL EXCEPTION: ControllerMessenger
Process: com.eaiinsurance, PID: 8340
android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Default constructor not found for type UXDivers.Effects.Droid.CornerRadiusEffect
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x0007b] in <184d4b3822534d1d819c4193b820d320>:0 
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <184d4b3822534d1d819c4193b820d320>:0 
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <184d4b3822534d1d819c4193b820d320>:0 
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00020] in <184d4b3822534d1d819c4193b820d320>:0 
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <184d4b3822534d1d819c4193b820d320>:0 
  at Xamarin.Forms.Effect.Resolve (System.String name) [0x00011] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.RoutingEffect..ctor (System.String effectId) [0x00006] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at UXDivers.Effects.Effects+CornerRadiusEffect..ctor () [0x00000] in <ea35e4c0ed4e4281bb624587c99ec0f0>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <184d4b3822534d1d819c4193b820d320>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00017] in <184d4b3822534d1d819c4193b820d320>:0 
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000a8] in <184d4b3822534d1d819c4193b820d320>:0 
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <184d4b3822534d1d819c4193b820d320>:0 
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <184d4b3822534d1d819c4193b820d320>:0 
  at System.Activator.CreateInstance[T] () [0x00015] in <184d4b3822534d1d819c4193b820d320>:0 
  at UXDivers.Effects.Effects.OnChanged[TEffect,TProp] (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x0005d] in <ea35e4c0ed4e4281bb624587c99ec0f0>:0 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00121] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle) [0x00000] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.Setter.Apply (Xamarin.Forms.BindableObject target, System.Boolean fromStyle) [0x000a4] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.Style.ApplyCore (Xamarin.Forms.BindableObject bindable, Xamarin.Forms.Style basedOn) [0x0001e] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.Style.Xamarin.Forms.IStyle.Apply (Xamarin.Forms.BindableObject bindable) [0x0003e] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.VisualElement+MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style) [0x00167] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.VisualElement+MergedStyle.set_Style (Xamarin.Forms.IStyle value) [0x0000d] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.VisualElement+<>c.<.cctor>b__213_6 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [0x00000] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00121] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.VisualElement.set_Style (Xamarin.Forms.Style value) [0x00000] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at EAIInsurance.QuoteCenterSelector.InitializeComponent () [0x00f52] in <cb16a4482005462b918abe2b3bb2b841>:0 
  at EAIInsurance.QuoteCenterSelector..ctor () [0x00006] in <cb16a4482005462b918abe2b3bb2b841>:0 
  at EAIInsurance.WelcomeStarterPage+<GetQuoteTapped>d__10.MoveNext () [0x00017] in <cb16a4482005462b918abe2b3bb2b841>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <184d4b3822534d1d819c4193b820d320>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <184d4b3822534d1d819c4193b820d320>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <e171f21acf2d45e3b1bb992d952798b7>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <e171f21acf2d45e3b1bb992d952798b7>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <e171f21acf2d45e3b1bb992d952798b7>:0 
  at (wrapper dynamic-method) System.Object:ce6e5413-8668-49d6-8922-1faabb1fe9f3 (intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:465)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:421)
	at android.support.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:235)
	at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:140)
	at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:123)
	at android.support.test.espresso.action.Tap.sendSingleTap(Tap.java:170)
	at android.support.test.espresso.action.Tap.access$100(Tap.java:31)
	at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:47)
	at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:136)
	at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:355)
	at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:242)
	at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by LeoHere** [comment]
@sadranyi take a look at #224

**Comment by dirivero** [comment]
I'm closing this as the outline of the Frame works fine in Android and iOS now.
