### ISSUE TITLE
 an unexpected status code '401 Unauthorized'

### ISSUE THREAD

**Issue by ukomiljon** [UXDivers/Grial-UI-Kit-Support#318]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'E:\Grial-marketezi\Grial\starter\marketezi\bin\Debug\marketezi.dll' could not be found	marketezi.iOS	E:\Grial-marketezi\Grial\starter\marketezi.iOS\CSC	1	Active
Error		NuGet Package restore failed for project marketezi.Droid: Unable to find version '2.5.2' of package 'UXDivers.Artina.Shared'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'UXDivers.Artina.Shared.2.5.2' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Shared.2.5.2' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://nuget.uxdivers.com/grial: The V2 feed at 'http://nuget.uxdivers.com/grial/Packages(Id='UXDivers.Artina.Shared',Version='2.5.2')' returned an unexpected status code '401 Unauthorized'.
.				
Error		NuGet Package restore failed for project marketezi.Droid: Unable to find version '2.5.2' of package 'UXDivers.Artina.Shared.Base'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'UXDivers.Artina.Shared.Base.2.5.2' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Shared.Base.2.5.2' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://nuget.uxdivers.com/grial: The V2 feed at 'http://nuget.uxdivers.com/grial/Packages(Id='UXDivers.Artina.Shared.Base',Version='2.5.2')' returned an unexpected status code '401 Unauthorized'.
.				
Error		NuGet Package restore failed for project marketezi.iOS: Unable to find version '2.5.2' of package 'UXDivers.Artina.Shared'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'UXDivers.Artina.Shared.2.5.2' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Shared.2.5.2' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://nuget.uxdivers.com/grial: The V2 feed at 'http://nuget.uxdivers.com/grial/Packages(Id='UXDivers.Artina.Shared',Version='2.5.2')' returned an unexpected status code '401 Unauthorized'.
.				
Error		NuGet Package restore failed for project marketezi.iOS: Unable to find version '2.5.2' of package 'UXDivers.Artina.Shared.Base'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'UXDivers.Artina.Shared.Base.2.5.2' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Shared.Base.2.5.2' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://nuget.uxdivers.com/grial: The V2 feed at 'http://nuget.uxdivers.com/grial/Packages(Id='UXDivers.Artina.Shared.Base',Version='2.5.2')' returned an unexpected status code '401 Unauthorized'.
.				
Error		NuGet Package restore failed for project marketezi: Unable to find version '2.5.2' of package 'UXDivers.Artina.Controls.Repeater'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'UXDivers.Artina.Controls.Repeater.2.5.2' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Controls.Repeater.2.5.2' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://nuget.uxdivers.com/grial: The V2 feed at 'http://nuget.uxdivers.com/grial/Packages(Id='UXDivers.Artina.Controls.Repeater',Version='2.5.2')' returned an unexpected status code '401 Unauthorized'.
.				
Error		NuGet Package restore failed for project marketezi: Unable to find version '2.5.2' of package 'UXDivers.Artina.Controls.Tab'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'UXDivers.Artina.Controls.Tab.2.5.2' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Controls.Tab.2.5.2' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://nuget.uxdivers.com/grial: The V2 feed at 'http://nuget.uxdivers.com/grial/Packages(Id='UXDivers.Artina.Controls.Tab',Version='2.5.2')' returned an unexpected status code '401 Unauthorized'.
.				
Error		NuGet Package restore failed for project marketezi: Unable to find version '2.5.2' of package 'UXDivers.Artina.Shared'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'UXDivers.Artina.Shared.2.5.2' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Shared.2.5.2' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://nuget.uxdivers.com/grial: The V2 feed at 'http://nuget.uxdivers.com/grial/Packages(Id='UXDivers.Artina.Shared',Version='2.5.2')' returned an unexpected status code '401 Unauthorized'.
.				
Error		NuGet Package restore failed for project marketezi: Unable to find version '2.5.2' of package 'UXDivers.Artina.Shared.Base'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'UXDivers.Artina.Shared.Base.2.5.2' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Shared.Base.2.5.2' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://nuget.uxdivers.com/grial: The V2 feed at 'http://nuget.uxdivers.com/grial/Packages(Id='UXDivers.Artina.Shared.Base',Version='2.5.2')' returned an unexpected status code '401 Unauthorized'.
.				
Error		The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'marketezi, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'marketezi.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	marketezi.Droid			
Error	CS0234	The type or namespace name 'Artina' does not exist in the namespace 'UXDivers' (are you missing an assembly reference?)	marketezi	E:\Grial-marketezi\Grial\starter\marketezi\App.xaml.cs	8	Active
Error	CS0234	The type or namespace name 'Artina' does not exist in the namespace 'UXDivers' (are you missing an assembly reference?)	marketezi	E:\Grial-marketezi\Grial\starter\marketezi\Helpers\Settings.cs	6	Active
Error	CS0234	The type or namespace name 'Artina' does not exist in the namespace 'UXDivers' (are you missing an assembly reference?)	marketezi	E:\Grial-marketezi\Grial\starter\marketezi\Properties\AssemblyInfo.cs	14	Active

**Comment by LeoHere** [comment]
Looks like it failed authenticating against our nuget package source. Please double check your credentials by visiting [this](http://nuget.uxdivers.com/grial) in your browser.

**Comment by ukomiljon** [comment]
I can go in Grial Admin with user name and password.
But http://nuget.uxdivers.com/grial/  
displays after login: 
-------------------------------------------------------------------------
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<service xmlns:atom="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app" xmlns="http://www.w3.org/2007/app" xml:base="http://nuget.uxdivers.com/grial/">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
</workspace>
</service>
--------------------------------------------------------------------------
During restore on VS output:
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm='grial'&targetFramework='portable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.

**Comment by LeoHere** [comment]
The fact that displays the XML means you successfully authenticate, so your credentials are fine. 

The problem seems to be in VS side. VS should ask you for your credentials when you try to access the Nuget package. Not sure why that is not the case in your setup.

Another option you have is to set your credentials in the `NuGet.config` file in the root directory (where the `sln` file resides). 

Something like this:

~~~
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />    
    <add key="GrialNuget" value="http://nuget.uxdivers.com/grial " />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSourceCredentials>
    <GrialNuget>
      <add key="Username" value="myLogin" />
      <add key="ClearTextPassword" value="myPassword" />
    </GrialNuget>
  </packageSourceCredentials>
</configuration>
~~~

Read [this](https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file) for more information.

**Comment by ukomiljon** [comment]
We are using VS2017 community edition.
is it any issue with VS2017 community edition?

I checked there is no any NuGet.config file.

UXDivers.Artina.Shared,UXDivers.Artina.Shared.Base, UXDivers.Artina.Shared.Repeater and UXDivers.Artina.Shared.Tab are issue,
but UXDivers.Effects is not issue

![image](https://user-images.githubusercontent.com/16934572/33305405-f7092cf4-d448-11e7-87de-82467ee65d7b.png)

**Comment by LeoHere** [comment]
VS2017 Community is not an issue.

If there is no `Nuget.config` (which is the most common case) you will need to create it.

`UXDivers.Effects` is a public Nuget package, so it make sense.

**Comment by ukomiljon** [comment]
I created Nuget.config:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />    
    <add key="grial" value="http://nuget.uxdivers.com/grial" />
  </packageSources>   
  <packageSourceCredentials>
    <grial>
      <add key="Username" value=".." />
      <add key="ClearTextPassword" value="..." />
    </grial>
  </packageSourceCredentials>
</configuration>

But not working.

**Comment by ukomiljon** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />    
    <add key="grial" value="http://nuget.uxdivers.com/grial" />
  </packageSources>
  




<activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSourceCredentials>
    <grial>
      <add key="Username" value=".." />
      <add key="ClearTextPassword" value="..." />
    </grial>
  </packageSourceCredentials>
</configuration>

**Comment by ukomiljon** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />    
    <add key="grial" value="http://nuget.uxdivers.com/grial" />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSourceCredentials>
    <grial>
      <add key="Username" value=".." />
      <add key="ClearTextPassword" value="..." />
    </grial>
  </packageSourceCredentials>
</configuration>
```

**Comment by ukomiljon** [comment]
Could you give me sample Nuget.config complete package?

**Comment by ukomiljon** [comment]
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='xamarinios10%7Cmonoandroid71%7Cportable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='xamarinios10%7Cmonoandroid71%7Cportable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='xamarinios10%7Cmonoandroid71%7Cportable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='xamarinios10%7Cmonoandroid71%7Cportable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='xamarinios10%7Cmonoandroid71%7Cportable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='xamarinios10%7Cmonoandroid71%7Cportable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='xamarinios10%7Cmonoandroid71%7Cportable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='xamarinios10%7Cmonoandroid71%7Cportable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='xamarinios10%7Cmonoandroid71%7Cportable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.
[grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='xamarinios10%7Cmonoandroid71%7Cportable45-net45%2Bwin8%2Bwp8'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.

**Comment by LeoHere** [comment]
@ukomiljon the `Nuget.Config` you specified looks just fine.

May be the name used in the `Nuget.Config` is the same as the one defined in `Tools->Options->Nuget` and is somehow confusing VS.

Please set the `Nuget.Config` to something like this.

~~~
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="GrialNugetConfig" value="http://nuget.uxdivers.com/grial" />
  </packageSources>
  <packageSourceCredentials>
    <GrialNugetConfig>
      <add key="Username" value="..." />
      <add key="ClearTextPassword" value="..." />
    </GrialNugetConfig>
  </packageSourceCredentials>
</configuration>
~~~

so we are sure there is no naming conflict. **Remember** to set your user name and password.

Then:
1. Restart VS
2. Open your solution and go to `Manage Nuget Packages for Solution`
3. Select the `GrialNugetConfig` source as shown in the image below

![image](https://user-images.githubusercontent.com/16000584/33429576-2ab8f796-d5ac-11e7-99c6-2404cdd76771.png)

4. Click Browse and wait for the package list to load.

**Comment by ukomiljon** [comment]
I did it, but not working, can u conform this:
Nuget.Config path:
![nuget config path](https://user-images.githubusercontent.com/16934572/33431508-895b0100-d60f-11e7-9921-e022d3ccb12e.png)

Nuget.Config:
![nuget](https://user-images.githubusercontent.com/16934572/33431617-fff4375a-d60f-11e7-811c-51772874121a.png)

Manage Nuget Packages for Solution:
![error](https://user-images.githubusercontent.com/16934572/33431861-eb39296e-d610-11e7-870c-040cc3661902.png)

**Comment by ukomiljon** [comment]
can you go in to my computer via teamviewer and solve it?

**Comment by ukomiljon** [comment]
Its trying to find v.2.5.2.  But there is 2.2.19
![error after restore](https://user-images.githubusercontent.com/16934572/33434369-0e6c7522-d61a-11e7-8e25-67c305d41df4.png)

it looks something wrong the version which I get.

**Comment by LeoHere** [comment]
@ukomiljon I'm seeing your attempts to signin in the logs. So, now the problem seems to be your password.

Please notice that in the screenshots you are using `Password` not the `ClearTextPassword`.  

![image](https://user-images.githubusercontent.com/16000584/33482360-6b4538a8-d677-11e7-9423-6554fb5d52be.png)

~~~
The `Password` requires the encrypted password, are you using the encrypted password there? Did you tried with the `ClearTextPassword`.

Also I see that in `packageSources` you are using naming the source `GrialNugetConfig` meanwhile in the `packageSourceCredentials` you are using `grial`.

**Comment by ukomiljon** [comment]
I changed Password  to  ClearTextPassword and GrialNugetConfig to  grial as you mentioned.
It works! Thank you very much!

**Comment by mistersam91** [comment]
Had the same problem, the solution explained by @LeoHere worked for me.

Except one thing : i modified the Nuget.config file in my AppData\Roaming\Nuget folder.

**Comment by OhSirius** [comment]
Also if you have set a wrong password in Nuget source and VS Stidio, then you can change it from StoragePassword in Windows
https://i.imgur.com/6RlmdL3.png
