### ISSUE TITLE
CachedImageRenderer.Init(); Failed to run on Android from Fresh Project download

### ISSUE THREAD

**Issue by mikeatmarvel** [UXDivers/Grial-UI-Kit-Support#361]
Upon downloading the Grail project from the uxdrivers website, then cleaning all, then restore nuget and update nuget, I received a fail to build when trying to run on Android simulator.  The failure was "There is no argument given that corresponds to the required formal parameter 'enableFastRenderer' of 'CachedImageRenderer.Init(bool?)'"

I can not run the application on Android.  iPhone runs perfectly fine.

**Comment by LeoHere** [comment]
@mikeatmarvel this is a breaking change introduced by [FFImageLoading](https://github.com/luberda-molinet/FFImageLoading) so users choose between using fast renderers or not. If you download the latest version of Grial you will see this parameter is set to `false`. AFAIK you can set it to `true` and it should work fine. We ship Grial with the parameter in `false` because we didn't fully tested yet.

**Comment by mikeatmarvel** [comment]
Leo-

I downloaded straight form Grail site as a fresh project and it does not run.  I also set the parameter to fastrendererenabled to false as well as true without success.  Thus, for me the project was not shipped with it at false.  Am I downloading the incorrect project from your site.  I love your product and want to upgrade to the PRO version but I want to resolve this before I commit.  Many thanks.

**Comment by LeoHere** [comment]
@mikeatmarvel my bad. I was talking about Grial 2.6 (.NET Standard based) with is still in RC mode. You probably downloaded 2.5.2 which depends on an older version of FFImageLoading, where that parameter was not required. 

I have just downloaded Grial based on 2.5.2, updated FFImageLoading to 2.3.4.

Changed `CachedImageRenderer.Init();` to `CachedImageRenderer.Init(false);` and run it, and it works as expected.

Please provide me more details about the error you are getting and when.

**Comment by mikeatmarvel** [comment]
@LeoHere Thank you for your help.  Here is the issue I am now running into after I changed to 

CachedImageRenderer.Init(false);

Android.Content.Res.Resources+NotFoundException: Resource ID #0x0
  at android.content.res.Resources$NotFoundException: Resource ID #0x0
  at at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
  at at android.content.res.Resources.getValue(Resources.java:1290)
  at at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded(AppCompatDrawableManager.java:234)
  at at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
  at at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
  at at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
  at at android.support.design.widget.TabLayout$Tab.setIcon(TabLayout.java:1388)
  at at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onCreateView(Native Method)
  at at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onCreateView(FragmentContainer.java:51)
  at at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
  at at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
  at at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
  at at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
  at at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
  at at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
  at at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
  at at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
  at at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
  at at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
  at at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
  at at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
  at at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
  at at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.n_onStart(Native Method)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.onStart(FormsAppCompatActivity.java:120)
  at at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
  at at android.app.Activity.performStart(Activity.java:6696)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
  at at android.app.ActivityThread.-wrap12(ActivityThread.java)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:154)
  at at android.app.ActivityThread.main(ActivityThread.java:6119)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by mikeatmarvel** [comment]
I need help!  As soon as possible.

Hello 

I need your help changing the android app setting package name 

from:
com.Carrotandroid

To

com.CarrotAndroid

We are having issues implementing Facebook login and other issues because of the case being wrong.  I need help as soon as possible!!!

**Comment by LeoHere** [comment]
@mikeatmarvel the change has been done. Just download the new license and change your app accordingly.
