### ISSUE TITLE
Android Exception after editing colors ... TaskDescription's primary color should be opaque

### ISSUE THREAD

**Issue by babernethy** [UXDivers/Grial-UI-Kit-Support#43]
I was trying to edit the default colors in the App.xaml - and this worked very well for iOS and initially for Android. At some point I must have changed a color that Android didn't agree with.  I never used any alpha channel / transparency colors.  But when trying to run I get the error below (only on Android).

I've since gone back to the default App.xaml and rerun the TT templates (both) but I'm still getting the error.  I'm not sure where to start looking to debug this.  If anyone else has seen this error, please let me know ...

Java.Lang.RuntimeException: Unable to start activity ComponentInfo{com.artina.grial.uikit/md58002a8511320679a2477ddb048442bf2.MainActivity}: java.lang.RuntimeException: **A TaskDescription's primary color should be opaque** ---> Java.Lang.RuntimeException: A TaskDescription's primary color should be opaque
  at --- End of managed exception stack trace ---
  at java.lang.RuntimeException: A TaskDescription's primary color should be opaque
  at at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:547)
  at at android.app.Activity.onApplyThemeResource(Activity.java:3696)
  at at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
  at at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2285)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
  at at android.app.ActivityThread.access$800(ActivityThread.java:155)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:135)
  at at android.app.ActivityThread.main(ActivityThread.java:5343)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:372)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
  --- End of inner exception stack trace ---
  at --- End of managed exception stack trace ---
  at java.lang.RuntimeException: Unable to start activity ComponentInfo{com.artina.grial.uikit/md58002a8511320679a2477ddb048442bf2.MainActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
  at at android.app.ActivityThread.access$800(ActivityThread.java:155)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:135)
  at at android.app.ActivityThread.main(ActivityThread.java:5343)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:372)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
  at Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
  at at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:547)
  at at android.app.Activity.onApplyThemeResource(Activity.java:3696)
  at at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
  at at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2285)
  at ... 10 more

Thoughts?

**Comment by jpbrocca** [comment]
Hi,
Please check that your AccentColor is opaque color (ie: #ff00ff00).

Best,
j

**Comment by babernethy** [comment]
If I manually updated the AccentColor in the Android Resources/Values/Colors.xml the error went away.  I am not sure why running the Colors.TT didn't update that automatically - did the first time.  I'll debug in Visual Studio and see what's up.  Thanks for the quick response on where to look.

**Comment by jpbrocca** [comment]
Ok I meant on the App.xaml, that way if you use an opaque color then the Colors.tt should work.
In any case I am glad that it is working to you now 😃
Let me know if you need anything else.

Best
JP

**Comment by babernethy** [comment]
Yes - I went back to the stock App.xaml - going to try to update it again and re-run the TT/T4 scripts to make sure the values propagate.  And make sure to have a "FF" alpha AccentColor to make Android happy ... very nice kit - thanks for creating it.

**Comment by jpbrocca** [comment]
Great, glad you like 😃
You need go try Gorilla Player too ;)

Best,
JP
