### ISSUE TITLE
The "LinkAssemblies" task failed unexpectedly.

### ISSUE THREAD

**Issue by soarying** [UXDivers/Grial-UI-Kit-Support#577]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'Test.Droid, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Test.Droid.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Test.Droid			

### Description

I am new to Grial, Just purchased basic license.
After I download the full screens and open it in VS2019. I got this error and can do nothing to run debug.
I am using windows visual studio2019. I have no problem to run new solution myself but not the one I downloaded.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version: none
- IDE: VS 2019 community
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by soarying** [comment]
![image](https://user-images.githubusercontent.com/41934391/57964959-a3656880-78fa-11e9-8cfd-72ddb8077061.png)

**Comment by soarying** [comment]
Forget the screenshot.
