### ISSUE TITLE
Grial 2.7.7 App Theme synchronization fails

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#586]
When building my App solution in VS 16.1.3, I found in the build output that Grial theme synchronization is failing

### Description

When building my App solution in VS 16.1.3, I found in the build output that Grial theme synchronization is failing

### Steps to Reproduce

1.  
2. 
3. 

### Expected Behavior

Theme synchronization to work

### Actual Behavior

In the app build proecess, the Grial Theme synchronization Task fails with the error - Object reference not set to an instance of an object.'. StackTrace:

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android:  
- Android Support Library Version: 
- Nuget Packages:

- Affected Devices:

### Screenshots / Build output 
1>------ Build started: Project: {My AppName}.iOS, Configuration: Debug iPhoneSimulator ------
1>Build started 6/14/2019 12:22:04 PM.
1>GrialTheme:
1>  [Grial] Initiating Syncrhonization for project 'c:\{My AppName path}.iOS.csproj'. Any Theme sync issues will be reported as a Build Warning. 
1>  Loading Settings from 'c:\{My AppName path}.iOS\Themes.json'
1>   - Importing 'ThemeSyncEnabled' overriding previous value
1>   - Importing 'iOSColorsFileName' overriding previous value
1>   - Importing 'AndroidColorsFile' overriding previous value
1>   - Importing 'ThemesFolder' overriding previous value
1>  Project 'c:\{My AppName path}.iOS.csproj' was recognized as an iOS Project.
1>  Initiating App.xaml lookup.
1>  [Error] 'Error 'Object reference not set to an instance of an object.' ocurred while analyzing Grial theme usage'. Exception message 'Object reference not set to an instance of an object.'. StackTrace: '   at UXDivers.Daas.Engine.ProjectItemsImpl.LoadProjectItems()
1>     at UXDivers.Daas.Engine.ProjectImpl.LoadProjectItems()
1>     at UXDivers.Daas.Engine.ProjectImpl.get_ProjectReferences()
1>     at UXDivers.Daas.ProjectExtensions.<GetAllReferencedProjects>d__0.MoveNext()
1>     at UXDivers.Daas.Commands.GrialAnalyzeSolutionCommand.Execute(IExecutionContext ctx)'
1>  [Grial] Terminating Syncrhonization

**Comment by IoTFier** [comment]
Can I please get some help on this issue ?

**Comment by LuizGsa21** [comment]
@IoTFier did you find a fix? I'm having the same issue.
