### ISSUE TITLE
Xamarin Forms 4.8.0.1364, grial:TabControl not working es expected

### ISSUE THREAD

**Issue by sajirkhan** [UXDivers/Grial-UI-Kit-Support#743]
### Description
After upgrade to latest version , 4.8.0.1364, Tab control content not rendering and strip render on middle of the page

### Steps to Reproduce

1. Upgrade xamarin forms to latest version - 4.8.0.1364
2. Run the project and open the page contains tab control
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by fcastro07** [comment]
Hi @sajirkhan 
The bug is fixed and will be available in the next version of UXDivers.Grial NuGet package, as soon as it's available I'll let you know.

**Comment by dirivero** [comment]
Hi @sajirkhan 
The fix for this is included in version 3.1.74-RC of the UXDivers.Grial package.

**Comment by pengham** [comment]
Hi. I updated to 3.1.74-RC and currently using Xamarin.Forms 4.7.0.968. If I update to version 4.8.0.1364, I will experience error when rebuild project.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'Android.Graphics.Path Xamarin.Forms.Platform.Android.GeometryExtensions::ToAPath(Xamarin.Forms.Shapes.Geometry,Android.Content.Context)' in assembly: 'Xamarin.Forms.Platform.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Xamarin.Forms.Rectangle Xamarin.Forms.Shapes.RectangleGeometry::get_Rect()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	OopsReship.Droid	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1645

**Comment by dirivero** [comment]
I'm closing this issue as this fix is part of final release 3.1.76.
