### ISSUE TITLE
WelcomePage errors out in OnAppearning - java.lang.IllegalStateException: Unable to parse composition

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#747]
Trying to run the sample Grial App for my app bundle using Grial 2.7.7 to review some of the XAML designs.
Upgraded XF to the latest stable 4.8.0.1364

### Description

Running app on Android fails when loading the WelcomePage.xaml
Your help will be appreciated.

09-07 19:39:21.642 D/AndroidRuntime( 4242): Shutting down VM
09-07 19:39:21.646 E/AndroidRuntime( 4242): FATAL EXCEPTION: main
09-07 19:39:21.646 E/AndroidRuntime( 4242): Process: {my app bundle}, PID: 4242
09-07 19:39:21.646 E/AndroidRuntime( 4242): java.lang.IllegalStateException: Unable to parse composition
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:74)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:67)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:91)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:84)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:158)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:27)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:133)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at android.os.Handler.handleCallback(Handler.java:873)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at android.os.Looper.loop(Looper.java:193)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at java.lang.reflect.Method.invoke(Native Method)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-07 19:39:21.646 E/AndroidRuntime( 4242): Caused by: com.airbnb.lottie.parser.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.parser.moshi.JsonReader.syntaxError(JsonReader.java:249)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:951)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:347)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:136)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:57)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:371)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:364)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:294)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:287)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieCompositionFactory.fromAssetSync(LottieCompositionFactory.java:181)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieCompositionFactory$2.call(LottieCompositionFactory.java:146)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at com.airbnb.lottie.LottieCompositionFactory$2.call(LottieCompositionFactory.java:143)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-07 19:39:21.646 E/AndroidRuntime( 4242): 	at java.lang.Thread.run(Thread.java:764)
**Java.Lang.IllegalStateException:** 'Loading...'

### Steps to Reproduce

Downloaded my Grial sample app for Grial 2.7.7; upgraded XF to 4.8.0.1364

### Expected Behavior

Should run animation on Welcome page without error 

### Actual Behavior

Gets error as shown in above 

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2019 16.7.2
- Platform Target Frameworks: 
  - iOS:  
  - Android:  8.1, 9
- Android Support Library Version: 
- Nuget Packages:
Shared - 
![image](https://user-images.githubusercontent.com/26844611/92440261-dc6dc000-f171-11ea-8204-6012fd333b2e.png)

Lottie packages - 
![image](https://user-images.githubusercontent.com/26844611/92440389-09ba6e00-f172-11ea-8485-1ceac76c2be6.png)

- Affected Devices: PIXEL 3 XL API 28 2

### Screenshots

Fails when running this piece of code 

```
		protected override void OnAppearing()
		{
			AnimationView.Play();

			Device.StartTimer(TimeSpan.FromMilliseconds(2500), () =>
			{
				if (isPageLoaded)
				{
					AnimationView.Play();
				}

				return isPageLoaded;
			});

		}
```

**Comment by IoTFier** [comment]
Hi @jpbrocca, how are you ?

Can you please help with this error ? 
Thank you

**Comment by IoTFier** [comment]
Hello @jpbrocca , can you please help ?
Thank you.
