### ISSUE TITLE
Release android application issues

### ISSUE THREAD

**Issue by dalton5** [UXDivers/Grial-UI-Kit-Support#760]
Hi,

I try to release my android app.

But I have the error and It's a blocker.

Can you help?

Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'System.Void App.Dev.Mobile.Droid.Resource::UpdateIdValues()' in assembly: 'App.Dev.Mobile.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Int32 UXDivers.Grial.Droid.Resource/Animation::abc_fade_in
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	App.Dev.Mobile.Android	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1645

**Comment by dalton5** [comment]
Hi,

Any news because it's a blocker to release my app. Thanks a lot

**Comment by jpbrocca** [comment]
Hi @dalton5,

could you please tell me?:

- your xamarin forms version
- your grial packages version
- your android build settings
- your android linker settings

Thanks
JP

**Comment by dalton5** [comment]
<PackageReference Include="Mono.Cecil">
      <Version>0.11.3</Version>
    </PackageReference>
 <PackageReference Include="Xamarin.Forms">
      <Version>4.8.0.1534</Version>
    </PackageReference>
 <PackageReference Include="UXDivers.Grial">
      <Version>3.1.76</Version>
    </PackageReference>

![image](https://user-images.githubusercontent.com/8339768/96870037-98f4ba00-1470-11eb-91e3-5d0cb931cb23.png)

**Comment by dirivero** [comment]
What Android Target Framework are you using?
The resource in the exception's stack trace comes from Rg.Plugins.Popup, is there an update available on that nuget?

**Comment by dalton5** [comment]
Android 10.0 (Q)

Where do you see it comes from Rg.Plugins.Popup? Isee UXDivers.Grial.Droid.Resource/Animation::abc_fade_in

**Comment by dalton5** [comment]
I upgraded my whole nugget packages.

I now have this issue related to grial kit again:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'Xamarin.Forms.View UXDivers.Grial.GrialNavigationBarRenderer::UXDivers.Grial.IGrialNavigationBarRenderer.get_Element()' in assembly: 'UXDivers.Grial.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Xamarin.Forms.View UXDivers.Grial.IGrialNavigationBarRenderer::get_Element()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	App.Dev.Mobile.Android	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1645

**Comment by dalton5** [comment]
Ok I am really sorry for the disturbance. I have manually removed all the bin folders. And I have no more errors. I investigate more and keep you in touch.

**Comment by dirivero** [comment]
That's great news! Let me know how it goes.
