### ISSUE TITLE
.Net Maui  net7.0 compatibility

### ISSUE THREAD

**Issue by marketdevsoft** [UXDivers/Grial-UI-Kit-Support#825]
Hi,

is possibile to work with new preview of .net 7 release of c# ? 

I tried it with my grial project but it seems that it is not possible .... 

Best reegards

Raffaele

**Comment by dirivero** [comment]
Hi Raffaele,

To target Net7 just update the UXDivers.GrialMaui package to version 4.0.66-RC
Once you do that, you should be able change the net6.0 targets in the csproj to net7.0 for android and iOS.

**Comment by marketdevsoft** [comment]
Thank you!
Retrying now after the update it works!

Best regards

Raffaele

**Comment by marketdevsoft** [comment]
Hi, 

i need to know what is the minimum requirement of android api to work properly with .NET 7 and Grial-Ui-Kit (4.0.66-RC at the moment...) ?
I test the full-application and it work fine with android13-api 33, but if i try it on physical device with android 11-api28, it crash when try to initialize picker :

11-29 08:41:24.160	HUAWEI LLD-L31	Error	25602	AndroidRuntime	java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference
	at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:141)
	at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:119)
	at crc640ec207abc449b2ca.ShellContentFragment.n_onAnimationEnd(Native Method)
	at crc640ec207abc449b2ca.ShellContentFragment.onAnimationEnd(ShellContentFragment.java:78)
	at android.view.animation.Animation.fireAnimationEnd(Animation.java:960)
	at android.view.animation.Animation.getTransformation(Animation.java:914)
	at android.view.animation.Animation.getTransformation(Animation.java:980)
	at android.view.animation.AnimationSet.getTransformation(AnimationSet.java:384)
	at android.view.animation.Animation.getTransformation(Animation.java:980)
	at android.view.View.applyLegacyAnimation(View.java:19975)
	at android.view.View.draw(View.java:20149)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.draw(View.java:20486)
	at android.view.View.updateDisplayListIfDirty(View.java:19294)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:740)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:746)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:861)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3583)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3379)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2711)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1633)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7943)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:893)
	at android.view.Choreographer.doFrame(Choreographer.java:812)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
